### ISSUE TITLE
Create a trace to test BP

### ISSUE THREAD

**Issue by pavelkryukov** [MIPT-ILab/mips-traces#1]
From mipt-mips created by [pavelkryukov](https://github.com/pavelkryukov) : MIPT-ILab/mipt-mips#36  

Currently no testing for Branch Prediction is made. We have to add the trace with huge amount of random branches.

**AMB:** Trace is implemented and shows sensitivity to BP size.

**Comment by pavelkryukov** [comment]
@NullByte4532 Is bubble sort a nice basis for this, how do you think?

**Comment by NullByte4532** [comment]
i have just tried to write a program that would jump around a tree of conditional jumps based on value of $t0, and change that value after almost every jump, so in the end every condition has been true and false at least one time. In the end $t0 has a value of 42. But instructions BLTZ and BGTZ do not seem to work in simulator.

**Comment by pavelkryukov** [comment]
Alexey, I think you didn’t get the goal of the trace correctly (that’s not your fault but mine, as it is not described clearly here). Let’s postpone the discussion until branch prediction lecture is delivered.

**Comment by pavelkryukov** [comment]
@NullByte4532 So, I think you get the idea for such trace. Random branches are not good as they are not predictable by any hardware. We need something regular but tricky, that's why bubble sort looks promising here.

**Comment by NullByte4532** [comment]
I cannot write an interesting branch prediction test when we have only one branching instruction implemented. Do i just write something using only beq or do i need to implement bgtz and bltz in the simulator first?

**Comment by pavelkryukov** [comment]
Why only one? We have four branches: `beq`, `bgtz`, `blez`, `bne` + all the jumps (see here: [Supported MIPS instructions](https://github.com/MIPT-ILab/mipt-mips/wiki/Supported-MIPS-instructions)). `bltz` could be implemented via `slt`:
```asm
slt $at, $X, $zero
bne $at, $zero, target
```

**Comment by pavelkryukov** [comment]
But if you really want to use `bltz` and other instructions, you should ask @inedostoev who is implementing them at the moment.

**Comment by pavelkryukov** [comment]
@NullByte4532 `bltz` is implemented.

**Comment by pavelkryukov** [comment]
@NullByte4532 Any news about bubble sort?
