### ISSUE TITLE
Change memtrace_based.s to contain more loops with loads

### ISSUE THREAD

**Issue by pavelkryukov** [MIPT-ILab/mips-traces#3]
From mipt-mips created by [ILAB-tester](https://github.com/ILAB-tester) : MIPT-ILab/mipt-mips#30  

**AMB:** mem_trace.s size is reduced

**Comment by NullByte4532** [comment]
So just to clarify, I need to write an assembly program that would access memory a lot, right?
If that is the case, would an implementation of bubble sort be ok?

**Comment by pavelkryukov** [comment]
Nope. Currently memtrace_based.s is something like this (speaking in C-code):

```c
volatile int* array = malloc(sizeof(int) * N);
volatile int buf = 0;
buf = array[23423];
buf = array[23943];
buf = array[97403];
buf = array[90220];
// .. a LOT of such lines ..
```

The idea is to convert it to something like this:

```c
volatile int* array = malloc(sizeof(int) * N);
uint16 offsets[] = { 23423, 23943, 97403, 90220 ... }

for (i = 0; i < M; ++i)
    buf = array[offsets[i]];
```

The memtrase_based.s was generated from that file: https://github.com/MIPT-ILab/mipt-mips/blob/master/simulator/infra/cache/t/mem_trace.txt. It was done by @igorsmir-ilab, he should know about the header.

But I like the idea of having bubble sort in our test database (in addition to this trace). There are some implementations for dynamic arrays: https://gist.github.com/manudatta/4283660 which we can extend to operate on a large static array.
